version: '3.7'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ./backend/foodgram
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./frontend/build:/var/www/frontend_build
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  data:
