# Generated by Django 4.0.7 on 2022-08-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-name"]},
        ),
        migrations.RenameField(
            model_name="recipe",
            old_name="text",
            new_name="recipe",
        ),
    ]
