# Generated by Django 4.0.7 on 2022-08-14 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_options_rename_text_recipe_recipe"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="recipe",
            new_name="text",
        ),
    ]
