# Generated by Django 4.0.7 on 2022-08-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_picture_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=32, verbose_name='Slug-адрес'),
        ),
    ]
