# Generated by Django 4.0.7 on 2022-09-04 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0014_alter_ingredient_measurement_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="is_favorited",
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_favorited",
            field=models.ManyToManyField(
                related_name="is_favorited",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписавшеся пользователи",
            ),
        ),
    ]
