# Generated by Django 4.1.1 on 2022-11-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0020_cart"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="unique_cart"
            ),
        ),
    ]
