# Generated by Django 4.1.1 on 2022-11-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0021_cart_unique_cart"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_cart",
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_cart"
            ),
        ),
        migrations.AddConstraint(
            model_name="ingredientquantity",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"), name="unique_recipe_ingredient"
            ),
        ),
    ]
