# Generated by Django 4.1.1 on 2022-11-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0022_remove_cart_unique_cart_cart_unique_cart_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="unique_favorite_recipe"
            ),
        ),
    ]
